/**
 * Shared TypeScript interfaces for the Elio Scaffold reference app.
 *
 * These types are auto-generated by the `generate-api-contracts` skill
 * and must match the Pydantic models in `back/agents/_reference/models.py`.
 *
 * Import in frontend via the `@shared-types` path alias:
 *   import type { ReferenceStep1Input } from "@shared-types";
 *
 * When you build a new agent, the `generate-api-contracts` skill will add
 * new interfaces here for your agent's input/output types.
 */

// ── Reference Agent — Step 1 ─────────────────────────────────────────────────

/** Input payload for the reference agent Step 1 (generate analysis). */
export interface ReferenceStep1Input {
  /** Username of the requester. */
  username: string;
  /** Main user request — the topic or question to analyze. */
  prompt: string;
  /** Optional additional context to guide the analysis. */
  context?: string;
  /** Output language: "fr" for French, "en" for English. Defaults to "fr". */
  language?: "fr" | "en";
  /** UI language for progress messages. Defaults to `language`. */
  interface_language?: "fr" | "en";
}

/** Result produced by Step 1 — a summary with key points. */
export interface ReferenceStep1Result {
  /** Concise answer or summary of the user's request. */
  summary: string;
  /** Key points extracted from the analysis (editable by user before Step 2). */
  key_points: string[];
}

// ── Reference Agent — Step 2 ─────────────────────────────────────────────────

/** Input payload for the reference agent Step 2 (expand into recommendations). */
export interface ReferenceStep2Input {
  /** Username of the requester. */
  username: string;
  /** Original user request from Step 1. */
  prompt: string;
  /** Result from Step 1, potentially edited by the user. */
  step1_result: ReferenceStep1Result;
  /** Output language: "fr" or "en". Defaults to "fr". */
  language?: "fr" | "en";
  /** UI language for progress messages. Defaults to `language`. */
  interface_language?: "fr" | "en";
}

/** Result produced by Step 2 — recommendations and next steps. */
export interface ReferenceStep2Result {
  /** Concrete, actionable recommendations derived from the key points. */
  recommendations: string[];
  /** Suggested next steps to act on the recommendations. */
  next_steps: string[];
  /** One-paragraph conclusion summarizing the analysis. */
  conclusion: string;
}

// ── SSE message shape (common to all agents) ─────────────────────────────────

/** Shape of every SSE message streamed by a backend step function. */
export interface SSEMessage {
  /** Step identifier (e.g. "beginning", "generating", "completed", "error"). */
  step: string;
  /** Human-readable progress message shown in the UI. */
  message: string;
  /** "in_progress" | "completed" | "error" */
  status: "in_progress" | "completed" | "error";
  /** Progress percentage 0–100. */
  progress: number;
  /** Result payload — only present when status === "completed". */
  result?: unknown;
  /** Error detail — only present when status === "error". */
  error?: string;
}
