"""Schemas for the _reference agent app.

This is the REFERENCE EXAMPLE — DO NOT MODIFY.
Copy the entire _reference/ folder and rename it for your use case.

Defines the TabSchema subclasses and output Pydantic models.
All TabSchema fields MUST have defaults (empty state = initial state).
"""

from pydantic import BaseModel, Field

from framework import TabSchema


# ─── Input tab ────────────────────────────────────────────────────────────────

class ReferenceInputTab(TabSchema):
    """Input data provided by the user."""

    prompt: str = Field("", description="Main user request")
    context: str = Field("", description="Optional additional context")
    lang: str = Field("fr", description="Output language: 'fr' or 'en'")


# ─── Output tab ───────────────────────────────────────────────────────────────

class ReferenceOutputTab(TabSchema):
    """Results generated by the agent steps."""

    # Step 1 result
    summary: str = Field("", description="Generated summary from Step 1")
    key_points: list[str] = Field(
        default_factory=list, description="Key points extracted by Step 1"
    )

    # Step 2 result
    recommendations: list[str] = Field(
        default_factory=list, description="Recommendations generated by Step 2"
    )
    next_steps: list[str] = Field(
        default_factory=list, description="Next steps suggested by Step 2"
    )
    conclusion: str = Field("", description="One-paragraph conclusion from Step 2")


# ─── Typed output models (used in app.py completed() calls) ───────────────────

class Step1Output(BaseModel):
    """Typed output for the 'generate' step."""

    summary: str = Field(description="Generated summary")
    key_points: list[str] = Field(default_factory=list, description="Key points extracted")


class Step2Output(BaseModel):
    """Typed output for the 'refine' step."""

    recommendations: list[str] = Field(
        default_factory=list, description="Concrete recommendations"
    )
    next_steps: list[str] = Field(
        default_factory=list, description="Suggested next steps"
    )
    conclusion: str = Field(description="One-paragraph conclusion")
